[features]
seeds = false
[programs.devnet]
market_sol = "ECpXc6PWu8ktZmJm4Qqit1zdeuSpTsAxzf3FmK9ULa7f"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/menduong/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint.ts"
test-buy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-buy.ts"
test-order = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-order.ts"
test-transfer = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-transfer.ts"